#!/usr/bin/env bash
sudo qemu-system-x86_64 \
  -m 1G \
  -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
  -drive if=pflash,format=raw,file=/usr/share/OVMF/OVMF_VARS_4M.fd \
  -drive file=distro.img,format=raw \
  -nographic