#!/bin/bash
set -e

mount -t proc  proc  /proc
mount -t sysfs sys   /sys
mount -t devtmpfs dev /dev

echo "Welcome to MINI"

setsid bash -c '
    exec /bin/bash </dev/tty1 >/dev/tty1 2>&1
' &
disown
setsid bash -c '
    exec /bin/bash </dev/ttyS0 >/dev/ttyS0 2>&1
'
